### ISSUE TITLE
[General] URL Issues in the website

### ISSUE THREAD

**Issue by sathishk** [sathishk/zols#83]
Steps:
Go to http://www.zols.org/
Click Guide or Fork us @ Github
Watch Browser URL

Expected Result:
User should be redircted to  http://www.zols.org/gulde.html or to http://gihub.com/sathish/zols

Actual Result:
Nothing happens

**Comment by saravanak** [comment]
Solved using instructions at 
https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/
